# Generated by Django 4.0.2 on 2023-07-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0002_remove_item_rating_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='total',
            new_name='item_price',
        ),
    ]
