# Generated by Django 4.0.2 on 2023-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0003_rename_total_checkout_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='item_name',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
