# Generated by Django 4.0.2 on 2023-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0004_alter_checkout_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
