# Generated by Django 4.0.2 on 2023-07-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0005_alter_checkout_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
