# Generated by Django 4.0.2 on 2023-07-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0006_checkout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image1', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image2', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image3', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image4', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_image5', models.FileField(blank=True, null=True, upload_to='images/banner')),
                ('banner_title1', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title2', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title3', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title4', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_title5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
