# Generated by Django 4.0.2 on 2023-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0007_bannerads'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='under_category',
            field=models.CharField(blank=True, choices=[('Home Appliance', 'Home Appliance'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture')], max_length=255, null=True),
        ),
    ]
