# Generated by Django 4.0.2 on 2023-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0009_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='buying_count',
            field=models.IntegerField(default=0),
        ),
    ]
