# Generated by Django 4.0.2 on 2023-08-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0010_alter_item_buying_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/category-banner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='offer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile_user',
            name='pro_pic',
            field=models.ImageField(default='static/images/logo/icon.png', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='offer_zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='static/images/logo/noimage.jpg', upload_to='images/items')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('offer', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MalieakalApp.user_registration')),
            ],
        ),
    ]
