# Generated by Django 4.0.2 on 2023-08-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0012_alter_offer_zone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_zone',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
