# Generated by Django 4.0.2 on 2023-08-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalieakalApp', '0013_alter_offer_zone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_zone',
            name='offer_price',
            field=models.FloatField(default=0),
        ),
    ]
